# Site metadata
title: Eric Peters
author:
  name: Eric Peters
  email: e_peters@alum.mit.edu
google_analytics: G-QEYP0WGDX8

# theme config
# theme: minima
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: "dark"
  appearance_toggle: true
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # options for "home" page
  home:
    title_projects: Portfolio
    title_blog: Blog Posts
    # title_misc_list: Details
    # title_old_projects: Old Projects